import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
golden_csv = PROJECT_ROOT / "eval" / "golden_set.csv"
df = pd.read_csv(golden_csv)

labels = {}

# Items 0-49
labels["52933"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Customer complains refund was issued without request; wanted item, not cancellation. Requires human specialist review into unauthorized cancellation.")
labels["93679"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer venting about past UPS delays; already cancelled orders locally. Carrier feedback; standard delay explanation.")
labels["47904"] = ("OTHER_GENERAL", "escalate", "N", "Customer complaint about phone support giving wrong number; venting about prior agent recordings. No specific order details.")
labels["51602"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Password reset loop failing repeatedly; requires authenticated security support.")
labels["83374"] = ("PRIME_MEMBERSHIP_BILLING", "escalate", "N", "Dispute over partner bank (ICICI) EMI interest discount calculation; requires finance/billing specialist.")
labels["16801"] = ("OTHER_GENERAL", "escalate", "N", "Frustrated customer demanding phone callback, claiming automated bots; uses #fraud and #poorcustomerservice hashtags.")
labels["57425"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Technical setup inquiry: how to activate Echo-only single device music plan for 3.99.")
labels["22526"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Login catch-22: customer is locked out and agent sent a link that requires logging in.")
labels["3732"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Direct statement of locked account; mandatory security escalation.")
labels["15302"] = ("OTHER_GENERAL", "escalate", "N", "Customer confirming details entered at provided URL; awaiting human resolution.")
labels["111750"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Technical compatibility query: does Facebook app on Fire OS support Facebook Live broadcast.")
labels["102607"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Preemptive inquiry regarding outer box damage on unopened Christmas gift laptop; explain holiday return window policy.")
labels["21858"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "International connection timeout (China GFW) combined with wrong password error.")
labels["96846"] = ("REFUND_RETURN_INQUIRY", "escalate", "Y", "Demanding immediate order cancellation with profanity; requires human agent intervention.")
labels["78815"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Delivery instructions feedback: parcel left in vulnerable spot where it could have been stolen; customer requests driver note.")
labels["99967"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "System restriction: damaged sample product returned, but site prevents reordering single-use samples. Needs agent override.")
labels["17661"] = ("OTHER_GENERAL", "auto", "Y", "Customer expressing gratitude and praise for support service; polite acknowledgment.")
labels["4859"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "2FA verification failure: SMS/call OTP not received, phone support was unable to resolve.")
labels["91300"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "UI confusion: customer received package with missing item, but returns portal asks for return of the missing item.")
labels["78774"] = ("OTHER_GENERAL", "auto", "Y", "General promotional query regarding announcement date for app quiz winners.")
labels["108229"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Critical fraud claim: broke college student lost money on camera order, demanding fraud department directly.")
labels["77635"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Repeat delivery failure on reorder within one week; customer expressing acute frustration with wasted time.")
labels["80806"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer inquiring whether sending DM with order number will help check recurring Prime shipping delays.")
labels["114312"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Customer asking why card was charged after order cancellation; explain authorization hold vs final settlement.")
labels["60245"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Cross-device streaming compatibility and Firestick setup confusion.")
labels["65763"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Inquiry about regional shipping restrictions on refurbished Kindle color variants to Northern Ireland.")
labels["64226"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Dispute over courier return shipping fee reimbursement from Amazon India.")
labels["95445"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Alexa voice command troubleshooting: songs not repeating when requested.")
labels["4788"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Emotional complaint: missed baby Halloween costume due to consecutive Prime delivery delays.")
labels["61023"] = ("PRIME_MEMBERSHIP_BILLING", "escalate", "N", "Billing grievance: customer claims loss of 4 months of Prime membership due to lack of notification.")
labels["58079"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Pre-order inquiry: which courier will be used for Xbox One X Scorpio Edition in UK.")
labels["109911"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Customer took paid work day off for missed delivery and demands compensation for wasted time.")
labels["35948"] = ("OTHER_GENERAL", "escalate", "N", "Sparse customer tweet with only an app screenshot URL; requires agent inspection.")
labels["105227"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer traveling for a month; delivery date conflicts with absence; explain address change or hold options.")
labels["95437"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Customer asking whether online chat support has been compromised/hacked; security concern.")
labels["69698"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Hostile customer alleging delivery agent committed fraud and demanding immediate payment.")
labels["25938"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Prime next-day delivery missing; untracked third-party seller parcel.")
labels["108132"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Inquiry regarding Prime shipping delivery speed expectations.")
labels["37625"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Critical account takeover: business Prime account hacked, unauthorized email change, locked out.")
labels["27886"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Direct question regarding refund processing timeframe to payment method.")
labels["16757"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Customer reporting ongoing confusion across multiple support agents regarding refund status.")
labels["93580"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Customer states damaged item was shattered and thrown in trash; explain returnless policy for broken glass.")
labels["67436"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Technical payment revision error when attempting to update credit card on existing orders.")
labels["63152"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Package marked delivered but not received; standard 24-36 hour carrier misdelivery protocol.")
labels["63826"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Order delivered as empty box (missing wallet); customer alleges fraud and provides phone/order details.")
labels["96743"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Wrong item delivered; customer urgently needs item and asks for replacement rather than return/refund.")
labels["16799"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Customer complaining replacement delivery timeline is much slower than buying new product; hostile hashtag.")
labels["75886"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Chronic delivery delay; multiple customer service contacts over 3 days with no courier response.")
labels["111908"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "General question about UK Prime delivery transit times showing Monday delivery instead of next-day.")
labels["16794"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Customer completed external escalation form and demands urgent refund solution.")

# Items 50-99
labels["115892"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Stolen high-value electronics (Fire HD 10 tablet and case); customer states theft and mentions filing police report.")
labels["38200"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Account hacked; customer unable to receive emails due to autoreply; requires security team handoff.")
labels["45529"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer provides order number with no text; standard self-service order tracking guidance.")
labels["47912"] = ("ACCOUNT_LOGIN_SECURITY", "auto", "Y", "Customer received suspicious email claiming Prime signup; can guide to check account directly to verify phishing vs real.")
labels["98587"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Defective fake product; return pickup rejected twice by courier; customer threatens lawsuit against seller.")
labels["62188"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Echo Dot 2nd Gen hardware troubleshooting: music playback stopping randomly despite fine connection.")
labels["21577"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "High hostility customer demanding immediate phone callback from management escalation point.")
labels["81755"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer shared details and requests delivery today or order cancellation.")
labels["118799"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Password reset link used 3x without success; customer threatening to leave for competitor.")
labels["77356"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Customer inquiring about refund process for an item lost by Amazon before return drop-off.")
labels["5312"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Password reset loop: reset link fails to grant access, still locked out.")
labels["105229"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Self-ship courier fee reimbursement inquiry; customer reluctant to arrange courier due to previous lost parcel.")
labels["78738"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer asking for customer support phone number regarding missing order.")
labels["111770"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Suspected carrier signature forgery on missing parcel, agent hung up on customer.")
labels["69813"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Customer alleging cheating, vows to tweet continuously until product is delivered.")
labels["118744"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer specifically demands escalation due to lack of action, uses #fraud.")
labels["86186"] = ("OTHER_GENERAL", "auto", "Y", "Digital gift card template glitch (birthday card printed Happy Holidays); can guide customer to reprint or chat.")
labels["69701"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Hypothetical damaged item question regarding Christmas gift in transit; provide standard return/replacement policy.")
labels["69669"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Seller unexpectedly cancelled and refunded order for a Christmas tree after Black Friday ended.")
labels["11084"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Technical issues with Fire Stick combined with Prime Video programming changes.")
labels["640"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "General product lifecycle question: is original Echo Show still supported.")
labels["67452"] = ("PRIME_MEMBERSHIP_BILLING", "escalate", "N", "Unauthorized billing charge incurred after customer had already cancelled membership.")
labels["29948"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Account hacked; customer locked out with zero access; specialist security escalation.")
labels["105185"] = ("OTHER_GENERAL", "escalate", "N", "Fragment reply ('I have not') lacking context; requires human specialist conversation review.")
labels["65665"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Package marked delivered with forged signature; customer alleges delivery team fraud.")
labels["16851"] = ("OTHER_GENERAL", "escalate", "N", "Customer unsatisfied with 500 INR token compensation; demands legal action against merchant.")
labels["63998"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Customer waiting on refund credit promised within 3 days; standard bank processing timeframe.")
labels["17686"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Customer inquiring about  charge during free trial; explain temporary card authorization hold.")
labels["108225"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Digital merchandise fraud loss; guarantee claim rejected; seeking fraud department escalation.")
labels["18689"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer questioning pricing above MRP and explicitly asking 'Should I sue you?'; legal threat policy.")
labels["58749"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Delivery status check: tracking shows delivered yesterday but item not received.")
labels["13157"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Customer requested order cancellation over the phone and confirms decision to stop waiting.")
labels["11981"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Repeated delivery deadline promises broken; customer expressing frustration with service.")
labels["56900"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Second consecutive replacement TV delivered damaged; systemic packaging failure requires manager review.")
labels["30493"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Customer reporting package tape was tampered and resealed with foreign tape.")
labels["102955"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Customer complaining about replacement-only policy on smartphones; can explain category return guidelines.")
labels["21027"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "International customer locked out, unable to access chat and unable to afford international calling.")
labels["73547"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer cancelled order after 2-day delivery slipped to 6 days; confirms cancellation.")
labels["98569"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Shattered glassware delivered; customer can hear broken glass inside unopened box; returnless replacement option.")
labels["43691"] = ("OTHER_GENERAL", "auto", "Y", "Customer expressing disappointment in courier selection policies and opting to boycott.")
labels["63886"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer reporting phone agent had no record of delivery delay; explain high-volume logistics backlog.")
labels["93589"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Inquiry on Prime order scheduled for today that has not left facility.")
labels["99796"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer explicitly states they want to file a case in Indian court; mandatory legal escalation.")
labels["76099"] = ("OTHER_GENERAL", "escalate", "N", "Frustrated customer who previously highlighted details asking why support is repeating questions.")
labels["35909"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Urgent delivery request asking Amazon to ensure delivery by end of day today.")
labels["42553"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Carrier communication breakdown: customer informed of return via email, disputes that package was damaged.")
labels["29943"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Hacked account: customer called 5 times for password reset email with zero resolution.")
labels["108184"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer informed by support that package is lost; guide to replacement/refund in portal.")
labels["9955"] = ("OTHER_GENERAL", "auto", "Y", "Customer expressing general frustration regarding warranty and customer service quality.")
labels["49976"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer threatening to lodge formal complaint in consumer court over indefinite delays; legal policy.")

print(f"Loaded {len(labels)} labels so far (0-99)")
# Items 100-149
labels["65711"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer asks whether to use another courier or different address for undelivered goods.")
labels["65625"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Email from CEO office lacks timeline for return pickup and refund credit; needs specialist.")
labels["44550"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Household Prime Music limitation: husband and wife wanting to stream on separate devices simultaneously.")
labels["54401"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Prime Student 6-month trial card verification issue.")
labels["80748"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Apple confirmed delivered phone was tampered and advised filing police report.")
labels["57456"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Amazon Pantry listing under Prime without free shipping; explain Pantry delivery fee structure.")
labels["111895"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer questioning when free next day delivery policy changed.")
labels["105302"] = ("OTHER_GENERAL", "escalate", "N", "Unable to chat or email in app, app forcing phone callback; customer requests DM support.")
labels["118749"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Active brushing/vendor fraud case: vendor using customer's address for return shipments.")
labels["13179"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Customer cancelling Prime membership due to perceived lack of benefits.")
labels["86084"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer worried about package tampering news; reassure with delivery protocols.")
labels["63873"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Order status: items in stock but no delivery date estimate given.")
labels["111802"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Waited a month for working monitor; received two consecutive defective units.")
labels["25841"] = ("ACCOUNT_LOGIN_SECURITY", "auto", "Y", "Customer confirming single login credentials.")
labels["16477"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Alexa app location glitch: installed in India but weather reports Seattle instead of Pune.")
labels["74582"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Customer questioning privacy risks of providing Aadhaar card for seller fraud investigation.")
labels["105307"] = ("OTHER_GENERAL", "auto", "Y", "Navigational query: where is specific contact option in mobile app.")
labels["75861"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Brief follow-up inquiring on delivery status after 1-2 week timeline.")
labels["24535"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Login loop between sign up for Prime and Manage Prime Membership page.")
labels["111769"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Phone agents hanging up on customer regarding courier delivery dispute.")
labels["27345"] = ("OTHER_GENERAL", "auto", "Y", "Frustrated tweet with error screenshot attempting to order tickets/items.")
labels["16798"] = ("OTHER_GENERAL", "escalate", "N", "Hostile customer claiming support team is lying about callbacks; uses #fraud.")
labels["64096"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "New user placed order, but account now says email not registered; identity/account lookup.")
labels["9123"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Customer unable to log in, worried about unauthorized account access.")
labels["38095"] = ("OTHER_GENERAL", "escalate", "N", "Customer stating third-party seller has not replied; A-to-z claim escalation.")
labels["91422"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Order missed revised estimated delivery date; standard delivery follow-up.")
labels["13189"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Purchased item arrived broken; asking how to initiate replacement in app.")
labels["40410"] = ("ACCOUNT_LOGIN_SECURITY", "auto", "Y", "Suspicious phishing email confirming Prime purchase; can advise how to report spoof emails.")
labels["17641"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Technical failure trying to raise return request 5 times in portal.")
labels["17260"] = ("ORDER_TRACKING_DELAY", "escalate", "N", "Repeat failure after prior agent assurance; customer demanding explanation.")
labels["52251"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Amazon jobs portal bug when logging in via LinkedIn OAuth.")
labels["50762"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer inquiring whether out-of-stock delay will impact Saturday delivery.")
labels["83494"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Customer received counterfeit local product, disputes Amazon gift balance refund instead of bank return.")
labels["73633"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Support link requires login to resolve login issue; catch-22.")
labels["21048"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Phone customer service unable to provide delivery update; customer checking via Twitter.")
labels["17193"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Customer complaining publicly about value of Prime membership.")
labels["67514"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Order replacement taking excessive time in Delhi; logistics inquiry.")
labels["86022"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer threatening court action over delayed refund compensation and distress.")
labels["37631"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Feature feedback: how to submit corrections for Amazon Music X-Ray lyrics.")
labels["96647"] = ("PRIME_MEMBERSHIP_BILLING", "auto", "Y", "Customer disputes extra packaging delivery charge.")
labels["65732"] = ("OTHER_GENERAL", "escalate", "N", "Emotional feedback regarding broken promises and lost trust.")
labels["91393"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Brother bought item as gift, arrived defective; guide to gift return process.")
labels["42558"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Delivery rescheduled, torn packing slip, damaged package; conflicting customer service answers.")
labels["65753"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer anxious about Xenoblade Chronicles 2 release day delivery; historical delivery issues.")
labels["96659"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Next-day delivery deadline missed; customer requests delivery today or will refuse package.")
labels["105215"] = ("OTHER_GENERAL", "auto", "Y", "Customer mentioning promo coupon aggregate RetailMeNot.")
labels["36567"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Royal Mail informed customer parcel is missing; guide to filing missing package in Your Orders.")
labels["31825"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Support advised customer to get police crime reference number for missing parcel.")
labels["73430"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Waiting for third-party seller response on return request; explain 48h seller response window.")
labels["74804"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Customer returned phone over 60 days ago; neither product nor money reimbursed.")

# Items 150-199
labels["73460"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Broken car steering phone holder received; photo provided; standard replacement flow.")
labels["109969"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Courier threw DVD box over fence damaging it; CS desk trying to charge extra for replacement.")
labels["111800"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Weeks without refund on returned items; supervisor allegedly lied to customer.")
labels["101753"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Package marked delivered yesterday but not received; carrier misdelivery steps.")
labels["19130"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Customer requesting doorstep pickup for return rather than paying courier self-return charges.")
labels["18709"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Alexa India skill missing Videos option to connect Fire TV.")
labels["3729"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Password reset 3 times, continues to show incorrect password.")
labels["35964"] = ("PRIME_MEMBERSHIP_BILLING", "escalate", "N", "Split order billing error: triple charged for second portion of shipment.")
labels["63901"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Amazon logistics delivered package; customer stuck in navigation loop reporting issue in app.")
labels["11065"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Hardware troubleshooting: hard reboot with SD card fails to resolve recurring error.")
labels["105050"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Damaged stationery pads received; guide to return/replacement.")
labels["101673"] = ("OTHER_GENERAL", "auto", "Y", "Customer providing app version and environment details.")
labels["1701"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Customer forgot email address on account; asks to search by bank details (security policy forbids).")
labels["69971"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Prepaid order delivered to wrong address and wrong item delivered.")
labels["44548"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Amazon Music streaming policy: can music be played on multiple devices simultaneously.")
labels["26932"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Echo feature inquiry: how to play podcasts via Alexa.")
labels["96815"] = ("OTHER_GENERAL", "auto", "Y", "Customer reporting pricing above MRP on listing; explain pricing guidelines and reporting.")
labels["36586"] = ("OTHER_GENERAL", "escalate", "N", "Customer offering to provide details on Twitter rather than app.")
labels["105018"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Inquiry on return postage liability for damaged item: buyer vs seller.")
labels["11064"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Device reboot issue recurring after temporary factory reset.")
labels["52197"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Parcels delivered next door due to previous resident using address; delivery instructions update.")
labels["80750"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Seller scammed: buyer returned phone with different IMEI ( loss); seller dispute.")
labels["67491"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Customer questioning delivery protocol for oversized parcels when recipient not home.")
labels["74649"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Device repair inquiry: customer wants device repaired rather than replaced; service center availability.")
labels["30016"] = ("ACCOUNT_LOGIN_SECURITY", "auto", "Y", "Login confusion between Vendor Central credentials and consumer contact form.")
labels["39576"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Recurring damaged book deliveries; books arriving creased or used.")
labels["118797"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Prime same-day delivery missed; inquiry on status.")
labels["46561"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Wrong edition of pre-ordered book delivered; customer wants correct edition reshipped.")
labels["71843"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "Y", "Password successfully changed but system still denies login.")
labels["105014"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Dispute over delivery damage mark on bag; customer provides image.")
labels["111814"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Clarification that order was placed 1 hour prior and has not yet shipped.")
labels["29664"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Spotify voice control setup on Echo when spouse is account owner.")
labels["86038"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Prime fulfillment critique: items in stock not shipping immediately.")
labels["64155"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Kindle cover delivery rescheduled to Monday; customer questioning Prime benefits with profanity.")
labels["115851"] = ("ACCOUNT_LOGIN_SECURITY", "auto", "Y", "Customer panicked about phishing emails, changed password; provide account security check steps.")
labels["28915"] = ("ACCOUNT_LOGIN_SECURITY", "escalate", "N", "Account identity verification demanding utility bill customer does not possess.")
labels["64224"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Customer care unreachable; order missing; demanding immediate refund.")
labels["98798"] = ("REFUND_RETURN_INQUIRY", "escalate", "N", "Waited 2 months for resolution; demands immediate action; uses #fraud.")
labels["45535"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Value pack missing 2 items; asks if missing pieces can be sent without returning whole pack.")
labels["44530"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Kindle Unlimited service not working on account; troubleshooting steps.")
labels["21572"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer demands management callback today or threatens consumer court filing.")
labels["93702"] = ("DAMAGED_WRONG_ITEM", "auto", "Y", "Delivery driver threw telescope over back gate marked 'handed to resident'; birthday gift damage concern.")
labels["69715"] = ("ORDER_TRACKING_DELAY", "auto", "Y", "Package out for delivery near delivery cutoff time; request to inform courier.")
labels["71915"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "4th bad experience: damaged headphones; customer care and third-party seller unable to resolve.")
labels["113791"] = ("PRODUCT_TECH_SUPPORT", "auto", "Y", "Firmware update confirmation for device issue.")
labels["64149"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Customer warning public about fraudulent pickup scams on Amazon India returns.")
labels["115937"] = ("OTHER_GENERAL", "auto", "Y", "Customer confirmed sending email with order details; polite acknowledgment.")
labels["17925"] = ("REFUND_RETURN_INQUIRY", "auto", "Y", "Self-return courier cost dispute; explain return shipping reimbursement policy.")
labels["65698"] = ("DAMAGED_WRONG_ITEM", "escalate", "N", "Three consecutive replacement CDs arrived broken in jiffy envelopes; packaging failure requires manager review.")
labels["109928"] = ("ESCALATION_HIGH_RISK", "escalate", "N", "Order cancelled without reason; customer explicitly threatens: 'see u in the consumer court'.")

print(f"Total labeled items: {len(labels)}")

# Apply to DataFrame
updated_rows = []
for idx, row in df.iterrows():
    msg_id = str(row['message_id'])
    if msg_id in labels:
        item = labels[msg_id]
        updated_rows.append({
            'message_id': row['message_id'],
            'text': row['text'],
            'thread_context': row.get('thread_context', ''),
            'true_intent': item[0],
            'has_good_grounding_example': item[2],
            'true_action': item[1],
            'notes': item[3]
        })
    else:
        print(f"Warning: message_id {msg_id} not in labels dictionary!")

out_df = pd.DataFrame(updated_rows)
out_df.to_csv(golden_csv, index=False)
print(f"[OK] Successfully saved {len(out_df)} hand-labeled golden examples to {golden_csv}")
print("\nNew Intent Distribution:")
print(out_df['true_intent'].value_counts().to_string())
print("\nNew Action Distribution:")
print(out_df['true_action'].value_counts().to_string())
